version: '3.5'

services:
  consul:
    image: consul
    container_name: consul
    restart: unless-stopped
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - 8500:8500
  
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
  
  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692

  seq:
    image: datalust/seq 
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80

  vault:
    image: vault
    container_name: vault
    restart: unless-stopped
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200

  fabio:
    image: fabiolb/fabio:1.5.13-go1.13.4
    container_name: fabio
    restart: unless-stopped
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=localhost:8500
    - FABIO_PROXY_STRATEGY=rr
    network_mode: host
    ports:
      - 9998:9998
      - 9999:9999